### PR TITLE
memoized backtrace_cleaner instance (Fixes #12)

### LINKED ISSUE #12: backtrace doesn't show the line of code executing the query
I run it 'out of the box' and got this:
```
2.1.1-railsexpress :004 > job.save
   (28.9ms)  BEGIN
    7 rows, 258 Bytes

  Jail Load (31.6ms)  SELECT  "jails".* FROM "jails" WHERE "jails"."email" = $1 LIMIT 1  [["email", "foo@bar.com"]]
    0 rows, 0 Bytes

    5 rows, 178 Bytes

    1 row, 2 Bytes

  Skill Load (30.8ms)  SELECT "skills".* FROM "skills" INNER JOIN "job_skills" ON "skills"."id" = "job_skills"."skill_id" WHERE "job_skills"."job_id" = $1  [["job_id", 27]]
    1 row, 74 Bytes

    6 rows, 227 Bytes

   (28.3ms)  ROLLBACK
 => false
2.1.1-railsexpress :005 >
```
On Rails 4.2.0 with PostgreSQL.

Am I doing something wrong?

### PR DESCRIPTION
**Pull request by mtyeh411**

### CODE REVIEW

**Comment by tjoyal** [comment]
Work as advertised, thanks!

**Comment by mtyeh411** [comment]
any chance this can get merged?  i have a few projects that i have to change Gemfiles for now :/

**Comment by sjmadsen** [comment]
Thanks for the PR, @mtyeh411. I've also invited both you and @tjoyal as contributors to the repo so that you can push directly to it, since I've been such a bum about my maintainer duties.

**Comment by tjoyal** [comment]
Thanks! o/

**Comment by mtyeh411** [comment]
@sjmadsen would you be willing to grant me gem ownership rights as well so the gem can be published?  my rubygems handle is `mtyeh411` (same as github handle)

cc @tjoyal

**Comment by sjmadsen** [comment]
Let's hold off on that for the moment. I want to review the other PRs and merge them if appropriate before a release goes out. I'd also like to get a feel for styles, etc. before taking that step. In the meantime, please feel free to tell me if you think a release is worth doing and I'll make a better effort to get it done.

**Comment by mtyeh411** [comment]
Okay. Makes sense. I was thinking that this pull request might make sense to publish since this gem is no longer fully functional on Rails 4.2+ otherwise

**Comment by sjmadsen** [comment]
Just to keep you both in the loop: I made a 3.0.9 gem and have been trying the past two nights to push it to Rubygems, but keep getting a "too many connection resets" error. I'll keep trying and/or open a support issue.

Regarding the other two open PRs: neither seemed important enough to block a new release, and introduce new adapters. One needs updates to merge cleanly, and both probably need a more serious look anyway. I also realized that this gem has no automated tests, which is kind of a drag. I opened a issue #15 to address this. Given how it hooks into ActiveRecord, I don't have any ideas right off on how to approach this. If you have any thoughts, let's start a discussion in that issue.

**Pull request merged**
